security:
  encoders:
    AppBundle\Entity\User:
      algorithm: bcrypt

  providers:
    login_provider:
      entity:
        class: AppBundle:User
        property: email

  firewalls:
    main:
      anonymous: ~
      form_login:
        login_path: login
        check_path: login
      provider: login_provider
      logout:
        path:   /logout
        target: /

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }
